export const IMAGES = new Map<string, string>([
  [
    'flag-success',
    'https://assetslogos.s3.eu-west-1.amazonaws.com/frontendassets/icons/icon__flag__success.svg',
  ],
  [
    'flag-failure',
    'https://assetslogos.s3.eu-west-1.amazonaws.com/frontendassets/icons/icon__flag__error.svg',
  ],
  [
    'flag-warning',
    'https://assetslogos.s3.eu-west-1.amazonaws.com/frontendassets/icons/icon__flag__warning.svg',
  ],
  [
    'alert-success',
    'https://assetslogos.s3.eu-west-1.amazonaws.com/frontendassets/icons/icon__alert__success.svg',
  ],
  [
    'alert-failure',
    'https://assetslogos.s3.eu-west-1.amazonaws.com/frontendassets/icons/icon__alert__failure.svg',
  ],
  [
    'alert-warning',
    'https://assetslogos.s3.eu-west-1.amazonaws.com/frontendassets/icons/icon__alert__warning.svg',
  ],
]);
